### ISSUE TITLE
关于全局的conifig.aomori_widgets没有给配置会报错

### ISSUE THREAD

**Issue by Cendeal** [lh1me/hexo-theme-aomori#33]
其实为啥要采用全局的config.aomori_xxx变量，而不采用theme.xxxx的局部变量。根据官网描述在theme下的_comfig.yml配置改变是不用重启的，把个人定制的变量放置theme下感觉会更加友好和方便。
theme/hexo-theme-aomori/_config.yml
```
version: 1.13.0
language: cn
aomori_logo: /images/avatar.jpg
aomori_menu:
  Home: /
  Archives: /archives
aomori_widgets:
  - toc # 文章导航
  - category  #文章分类
  - tag # 文章标签
  - recent_posts  # 最新文章
  - archive #文章归档
```
然后使用就是在ejs使用theme.aomori_widgets这样会更香些，个性定制更加灵活
