### ISSUE TITLE
關於社交媒體 icon 無法正常顯示

### ISSUE THREAD

**Issue by Robeeerto** [lh1me/hexo-theme-aomori#46]
先謝謝大大做的這個主題，我個人非常喜歡。
但自己在設置的過程中發現沒辦法正確的顯示 icon
```
aomori_social:
  -
    icon: github
    type:
    url: my-github-url
```
頁面上是能夠按到超連結的，但卻沒辦法顯示圖案，不知道是我哪裡做錯了
感謝您～
