### ISSUE TITLE
代码高亮没生效

### ISSUE THREAD

**Issue by teslapatrick** [lh1me/hexo-theme-aomori#75]
问题：
        默认配置下，全局 _config.yml 配置文件中，
```
highlight:
  enable: true
prismjs:
  enable: false
```
`hexo g`和`hexo serve`从`md`文件生成的页面中，代码高亮的样式明显不对。不清楚什么原因，查过hexo官方资料未解决。有什么解决办法吗？
