### ISSUE TITLE
valine配置项不起作用

### ISSUE THREAD

**Issue by imcloud** [lh1me/hexo-theme-aomori#76]
```
aomori_valine:
  enable: true
  appId: ''
  appKey: ''
  placeholder: '聊点什么...'
```

按官方文档配置了占位字符，重启服务后仍然是默认的just go go
尝试了其他配置项，均无效。
